Repository AY2223S1-CS2113T-W11-2/tp, pull requests merged in 2022-10, with the labels that each got.

#36 Swapped Type and Name parameters
  src/main/java/computercomponentchooser/EditParser.java
Labels: enhancement

#38 Fixed unsafe warning message
  src/main/java/computercomponentchooser/LinkedHashMap2D.java
Labels: enhancement

#42 Refactored EditParser
  data/build1.txt
  data/builds.txt
  src/main/java/computercomponentchooser/EditParser.java
Labels: enhancement

#43 Refactor Parser and Added Monitor Component
  src/main/java/computercomponentchooser/Build.java
  src/main/java/computercomponentchooser/EditParser.java
  src/main/java/computercomponentchooser/Parser.java
  src/main/java/computercomponentchooser/components/Monitor.java
  src/main/java/computercomponentchooser/storage/Storage.java
Labels: enhancement

#44 Added Other Class and Export Feature
  data/build1.txt
  data/exportAllBuildsText.txt
  data/export_build1.txt
  data/working.txt
  export_working.txt
  src/main/java/computercomponentchooser/Build.java
  src/main/java/computercomponentchooser/ComputerComponentChooser.java
  src/main/java/computercomponentchooser/EditParser.java
  src/main/java/computercomponentchooser/Parser.java
  src/main/java/computercomponentchooser/components/Other.java
  src/main/java/computercomponentchooser/export/ExportText.java
  src/main/java/computercomponentchooser/storage/Storage.java
Labels: enhancement

#47 Added compatibility checks for socket (cooler) and formFactor
  data/build1.txt
  src/main/java/computercomponentchooser/Build.java
Labels: enhancement

#48 Added Expansion Slot Compatibility
  data/build1.txt
  src/main/java/computercomponentchooser/Build.java
Labels: enhancement

#49 Added exportCSV and Changed order of params in Cooler
  data/build1.txt
  data/build2.txt
  data/builds.txt
  data/exportAllBuildsCSV.csv
  src/main/java/computercomponentchooser/Build.java
  src/main/java/computercomponentchooser/Parser.java
  src/main/java/computercomponentchooser/components/Case.java
  src/main/java/computercomponentchooser/components/Component.java
  src/main/java/computercomponentchooser/components/Cooler.java
  src/main/java/computercomponentchooser/components/Cpu.java
  src/main/java/computercomponentchooser/components/Drive.java
  src/main/java/computercomponentchooser/components/Gpu.java
  src/main/java/computercomponentchooser/components/Memory.java
  src/main/java/computercomponentchooser/components/Monitor.java
  src/main/java/computercomponentchooser/components/Motherboard.java
  src/main/java/computercomponentchooser/components/Other.java
  src/main/java/computercomponentchooser/components/PowerSupply.java
  src/main/java/computercomponentchooser/export/ExportCsv.java
Labels: enhancement

#51 Added a filter feature and modified find feature
  data/build2.txt
  src/main/java/computercomponentchooser/Build.java
  src/main/java/computercomponentchooser/BuildManager.java
  src/main/java/computercomponentchooser/EditParser.java
  src/main/java/computercomponentchooser/Parser.java
Labels: enhancement

#54 refactored addParse in edit parser
  data/build2.txt
  data/exportAllBuildsCSV.csv
  data/export_build2.txt
  src/main/java/computercomponentchooser/EditParser.java
Labels: enhancement

#55 Added assertions
  src/main/java/computercomponentchooser/EditParser.java
  src/main/java/computercomponentchooser/Parser.java
Labels: enhancement

#56 Exception Handling
  data/a.txt
  data/builds.txt
  src/main/java/computercomponentchooser/BuildManager.java
  src/main/java/computercomponentchooser/EditParser.java
  src/main/java/computercomponentchooser/Parser.java
  src/main/java/computercomponentchooser/exceptions/NegativeNumberException.java
Labels: enhancement

#60 Added parts of UG
  docs/UserGuide.md
Labels: documentation

#63 Added to UG
  data/builds.txt
  data/exportAllBuildsText.txt
  data/export_testbuild.txt
  data/testbuild.txt
  docs/UserGuide.md
  src/main/java/computercomponentchooser/BuildManager.java
Labels: documentation

#64 Fixed filter method
  src/main/java/computercomponentchooser/Parser.java
Labels: bug

#65 Added JavaDocs to UI, Parser, EditParser, Export, LinkedHashMap2D, Build and ComputerComponentChooser
  src/main/java/computercomponentchooser/Build.java
  src/main/java/computercomponentchooser/ComputerComponentChooser.java
  src/main/java/computercomponentchooser/EditParser.java
  src/main/java/computercomponentchooser/LinkedHashMap2D.java
  src/main/java/computercomponentchooser/Parser.java
  src/main/java/computercomponentchooser/Ui.java
  src/main/java/computercomponentchooser/export/ExportCsv.java
  src/main/java/computercomponentchooser/export/ExportText.java
Labels: documentation

#67 Added JavaDocs for BuildManager and Exception classes
  src/main/java/computercomponentchooser/BuildManager.java
  src/main/java/computercomponentchooser/exceptions/BlankStringException.java
  src/main/java/computercomponentchooser/exceptions/DuplicateBuildException.java
  src/main/java/computercomponentchooser/exceptions/NegativeNumberException.java
  src/main/java/computercomponentchooser/exceptions/UnknownCommandException.java
  src/main/java/computercomponentchooser/exceptions/UnlistedBuildException.java
Labels: documentation

#69 Removed Don Roe from AboutUs and attempt fix of DG
  docs/AboutUs.md
  docs/DeveloperGuide.md
Labels: bug, documentation

#72 Fixed logic for check socket compatibility
  data/build1.txt
  src/main/java/computercomponentchooser/Build.java
Labels: enhancement

#76 Basic Class Diagram for BuildManager
  docs/BuildManager.puml
  docs/DeveloperGuide.md
  src/main/java/computercomponentchooser/Build.java
  src/main/java/computercomponentchooser/storage/Storage.java
Labels: documentation

#80 Added Storage section to DG
  docs/DeveloperGuide.md
  docs/Storage.puml
  docs/images/Storage.png
Labels: documentation

#79 Added to DG
  docs/DeveloperGuide.md
  docs/images/BuildManager.png
  docs/puml/BuildManager.puml
Labels: documentation

#84 Added Sequence Diagram for the adding of builds
  docs/DeveloperGuide.md
  docs/images/BuildManagerAddBuildSequence.png
  docs/puml/BuildManagerAddBuildSequence.puml
Labels: documentation
