Repository AY2223S1-CS2113T-W11-2/tp, pull requests merged in 2022-11, with the labels that each got.

#123 Minor bug fix
  data/builds.txt
  data/exportAllBuildsText.txt
  docs/UserGuide.md
  src/main/java/computercomponentchooser/EditParser.java
  src/main/java/computercomponentchooser/Parser.java
  src/main/java/computercomponentchooser/Ui.java
Labels: bug

#125 Minor bug fix
  docs/UserGuide.md
  src/main/java/computercomponentchooser/EditParser.java
  src/main/java/computercomponentchooser/Parser.java
  src/main/java/computercomponentchooser/Ui.java
Labels: bug

#131 Added colons to build sequence diagram and added some tests for ComponentsTest
  docs/puml/BuildSequence.puml
  src/test/java/computercomponentchooser/ComponentsTest.java
Labels: documentation, test

#132 Added more tests to ComponentsTest
  src/test/java/computercomponentchooser/ComponentsTest.java
Labels: test

#133 Fixed inconsitency Motherboard getDetails formFactor -> Form Factor
  src/main/java/computercomponentchooser/components/Motherboard.java
  src/test/java/computercomponentchooser/ComponentsTest.java
Labels: bug

#135 Added UnlistedComponentTypeException
  data/build1.txt
  data/builds.txt
  src/main/java/computercomponentchooser/EditParser.java
  src/main/java/computercomponentchooser/exceptions/UnlistedComponentTypeException.java
Labels: bug

#136 Change buildmanager from HashMap to LinkedHashMap
  src/main/java/computercomponentchooser/BuildManager.java
Labels: enhancement

#137 Added Sequence Diagram for Storage
  data/a.txt
  data/builds.txt
  data/testbuild.txt
  docs/DeveloperGuide.md
  docs/images/StorageLoadSequence.png
  docs/images/StorageSaveBuildSequence.png
  docs/images/StorageSaveComponentSequence.png
  docs/puml/StorageLoadSequence.puml
  docs/puml/StorageSaveBuildSequence.puml
  docs/puml/StorageSaveComponentSequence.puml
  src/main/java/computercomponentchooser/storage/Storage.java
Labels: documentation

#138 Added sequence diagrams for BuildManager part in DG
  docs/DeveloperGuide.md
  docs/images/Build.png
  docs/images/BuildManager.png
  docs/images/BuildManagerAddBuildSequence.png
  docs/images/BuildManagerFilterSequence.png
  docs/images/BuildManagerFindSequence.png
  docs/images/BuildManagerListSequence.png
  docs/images/Storage.png
  docs/puml/BuildManagerAddBuildSequence.puml
  docs/puml/BuildManagerFilterSequence.puml
  docs/puml/BuildManagerFindSequence.puml
  docs/puml/BuildManagerListSequence.puml
  docs/puml/Storage.puml
Labels: documentation

#140 Added more puml files and Added export interface for better oop
  data/exportAllBuildsCSV.csv
  docs/DeveloperGuide.md
  docs/images/BuildSequence.png
  docs/images/BuildSequenceCheckGpuSlot.png
  docs/images/BuildSequenceGetTotalPower.png
  docs/puml/BuildSequence.puml
  docs/puml/BuildSequenceCheckGpuSlot.puml
  docs/puml/BuildSequenceGetTotalPower.puml
  src/main/java/computercomponentchooser/export/Export.java
  src/main/java/computercomponentchooser/export/ExportCsv.java
  src/main/java/computercomponentchooser/export/ExportText.java
Labels: documentation, enhancement

#143 Added Bye feature to the UG
  docs/UserGuide.md
Labels: documentation

#144 Added to DG for build and Export, minor naming fix in exportCSV class
  docs/DeveloperGuide.md
  docs/images/Export.png
  docs/puml/Export.puml
  src/main/java/computercomponentchooser/export/ExportCsv.java
Labels: documentation, enhancement

#145 Update DG, remove user story that is not implemented
  docs/DeveloperGuide.md
  src/main/java/computercomponentchooser/EditParser.java
  src/main/java/computercomponentchooser/Parser.java
Labels: documentation

#146 Added some hyperlinks to UG
  docs/UserGuide.md
Labels: documentation

#147 Added Architecture diagram, corrected Component Diagram to make it more readable and other minor fixes
  docs/DeveloperGuide.md
  docs/images/Architecture.png
  docs/images/Build.png
  docs/images/ComponentEdited.png
  docs/puml/Architecture.puml
  docs/puml/Build.puml
  docs/puml/ComponentEdited.puml
Labels: documentation

#148 Added some tests for Parser and EditParser
  src/main/java/computercomponentchooser/ComputerComponentChooser.java
  src/main/java/computercomponentchooser/Parser.java
  src/test/java/computercomponentchooser/ComponentsTest.java
  src/test/java/computercomponentchooser/EditParserTest.java
  src/test/java/computercomponentchooser/ParserTest.java
Labels: test

#149 Added more explanation to Storage feature in DG
  docs/DeveloperGuide.md
  docs/UserGuide.md
Labels: documentation

#150 Added testing main mode to DG
  data/build1.txt
  data/build2.txt
  data/exportAllBuildsCSV.csv
  data/export_build2.txt
  data/export_testbuild.txt
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/team/gitpancaked.md
Labels: documentation

#151 Added to Build Editing Mode manual testing
  docs/DeveloperGuide.md
  docs/team/Heinrich Koh Kaiyang.md
Labels: documentation

#152 Added my PPP
  docs/AboutUs.md
  docs/team/gitpancaked.md
Labels: documentation

#155 Added PPP
  docs/AboutUs.md
  docs/team/lcsroy.md
Labels: documentation

#157 Update README.md
  docs/README.md
  docs/_config.yml
  docs/team/p0tatochips.md
Labels: documentation

#158 Update p0tatochips.md
  docs/team/p0tatochips.md
Labels: documentation

#164 Update UG
  docs/UserGuide.md
Labels: documentation
